name       : helix
version    : '23.05'
release    : 1
source     :
    - https://github.com/helix-editor/helix/releases/download/23.05/helix-23.05-source.tar.xz : c1ca69facde99d708175c686ce5bf3585e119e372c83e1c3dc1d562c7a8e3d87
license    : MPL-2.0
homepage   : https://helix-editor.com/
component  : editor
summary    : post-modern text editor
description: |
    A post-modern text editor.
    It's a joke. If Neovim is the modern Vim, then Helix is post-modern.
networking : true
builddeps  :
    - cargo
    - git
setup      : |
    git config --global --add safe.directory '*'
build      : |
    cargo build --release --locked
install    : |
    mkdir -p $installdir/usr/lib/helix
    rm -r $workdir/runtime/grammars/sources
    cp -r $workdir/runtime $installdir/usr/lib/helix
    install -Dm00755 $workdir/target/release/hx $installdir/usr/lib/helix/hx
    install -Dm00777 $pkgfiles/hx $installdir/usr/bin/hx

